columns:
      longitude: float
      latitude: float
      housing_median_age: float
      total_rooms: float
      total_bedrooms: float
      population: float
      households: float
      median_income: float
      median_house_value: float
      ocean_proximity: category

target column: median_house_value

# the only categorical feature and the only present values on it
domain_value:
      ocean_proximity:
            - <1H OCEAN
            - INLAND
            - ISLAND
            - NEAR BAY
            - NEAR OCEAN